### ISSUE TITLE
Map: Make work on responsive viewports

### ISSUE THREAD

**Issue by cjdd3b** [striblab/20180615-house-explainer#1]
This might be murdery, so I'll take a look as well. But the respsonsiveness has to play nice with both the map and the timing of the scroll stuff.

**Comment by jeffhargarten** [comment]
The map is now responsive. The scrolly bits and zooming still need to be fixed.

**Comment by jeffhargarten** [comment]
Okay I now have a much more flexible and scalable solution for map zoom responsiveness. Some refinement is still needed, but the functionality is there.

**Comment by jeffhargarten** [comment]
Not quite there yet, but closer than before

**Comment by jeffhargarten** [comment]
It's working adaptively, by zooming in on the centroids of specific states depending upon whether the viewport is mobile or desktop. What's not currently accounted for are sizes in between. And while the map size is responsive, the zoom trigger is not.

**Comment by jeffhargarten** [comment]
The zoom centering is now adaptive and works on all tested viewports. There are definitely some spacing and issues with the scrolly bits to fix still

**Comment by cjdd3b** [comment]
Nice! I'm taking a run through text edits today but will take a look when
done.

**Comment by cjdd3b** [comment]
Assuming the spacing/scrolly issues might be identified by #13, #14 and #15?

**Comment by cjdd3b** [comment]
Also if the zoom ends up being too much of a pain, we can refactor to not include it. There's probablyy another way to do this where the map stays entirely focused on MN, for example. Might be worth each of us taking a look, maybe pairing on it tomorrow or Monday, then making a call on best approach.

**Comment by jeffhargarten** [comment]
Nullified the zooming issues
