### ISSUE TITLE
Map: Fix space at top on upscroll

### ISSUE THREAD

**Issue by cjdd3b** [striblab/20180615-house-explainer#13]
There's a weird chunk of whitespace between the map and the text that appears when scrolling back up from the bottom.

Forcing a re-render of the map (`map.init()`) on exit of the first step (if `direction == up`) seems to be a hacky way to deal with this, but there must be a better solution. Also not sure what the root cause is.

**Comment by jeffhargarten** [comment]
Root cause could be the zoom trigger targeting the centroid of the nation shape. Probably just needs some extra pixel padding on the x and y within the _zoom_out() function
