### ISSUE TITLE
Map: Add data to shapefile

### ISSUE THREAD

**Issue by cjdd3b** [striblab/20180615-house-explainer#2]
Good to dump in some of this data so it's not buried in the code. Also might be useful to highlight counties by things like congressional/presidential margin rather than random colors.

  - [x] Competitive districts
  - [x] 2016 congressional margin
  - [x] 2016 presidential margin

**Comment by jeffhargarten** [comment]
fields added to the shapefile:

statePostal (string) - state abbreviation for future use
party (string) - party currently holding district
race_margin (real) - 2016 congressional race margin with positive indicating GOP win, negative DEM win
race_margin (real) - 2016 presidential race margin with positive indicating Trump win, negative Clinton win
cpvi (integer) - Cook Partisan Voting Index score, positive R and negative D
rating (string) - Cook race rating
status (string) - Whether a seat is Open, vacant, etc. A null value indicates an incumbant
compete (boolean 1 or 0) - whether or not the race is considered competitive 

note: expanded the shapefile size to about 2MB
