### ISSUE TITLE
Map: Smooth out zooming?

### ISSUE THREAD

**Issue by cjdd3b** [striblab/20180615-house-explainer#3]
Notice how it's a little choppy when it moves into Minnesota. But some D3 tweaking could probably smooth it out. See examples like [this](https://bl.ocks.org/mbostock/3828981) and [this](https://bl.ocks.org/mbostock/3828981) and [this](https://bl.ocks.org/iamkevinv/0a24e9126cd2fa6b283c6f2d774b69a2).

Not super important, but could be a good optimization that we'd take advantage of if/when we do things like this again. Think state-to-county maps on election night.

Notice how this a little smoother, for example: https://www.nytimes.com/elections/results/president

**Comment by jeffhargarten** [comment]
Changing the transition duration to 300 seems to have improved this
