### ISSUE TITLE
Map: Districts shapefile might be too simplified ...

### ISSUE THREAD

**Issue by cjdd3b** [striblab/20180615-house-explainer#4]
Just a note to self. Might want to get a little more detail in there.

**Comment by jeffhargarten** [comment]
Running into some mapshaper projection issues when trying to do this. File size of geojson also grows significantly. Will revisit on Monday.

**Comment by cjdd3b** [comment]
Done with this. Full process is automated now in `sources/get_map.sh`. Also pulls in your races.csv file.
