### ISSUE TITLE
Charts: Polish

### ISSUE THREAD

**Issue by cjdd3b** [striblab/20180615-house-explainer#9]
- [x] Shrink sizes to 700-some pixels
- [x] Revisit styles, headlines, captions, font sizes, etc.

TKTK

**Comment by jeffhargarten** [comment]
Got some work done on this today. That CPVI chart styles are still heavily borked due to some phantom template CSS making all the grid lines and labels invisible

**Comment by jeffhargarten** [comment]
Made some headway on polishing these up. Further tweaks can be decided in committee
